### ISSUE TITLE
Release version 0.18.0

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#106]
We need to:
* tag the source code
* distribute packages (Bret has already created them): where should we put them?
* promote it on reddit, on the google group and on twitter
* update the readme
* anything else?

**Comment by ftomassetti** [comment]
* Readme updated
* Release created under the releases page: it contains the binary packages and created the tag

**Comment by psi29a** [comment]
packages go in the release itself, go to releases and click on the tag to edit it
down at the bottom, just drag & drop the binaries there

**Comment by psi29a** [comment]
Normally you want to update the readme (or anything in the repo) before you tag a release.

**Comment by ftomassetti** [comment]
Right, I will move the tag

**Comment by ftomassetti** [comment]
Ok, now the tag should point to the correct README

**Comment by psi29a** [comment]
You'll need to re-upload the binaries and release documentation on the new tag. ;)

**Comment by ftomassetti** [comment]
I don't think so: the release was marked as draft after I changed the tag but now I published it and the binaries should be fine (I mean, the binaries will contain the old README.md but probably we do not want to go over the whole process of reg-generating them. Do we?)

**Comment by psi29a** [comment]
Super! :) I thought the binaries were lost when tag was replaced.

**Comment by ftomassetti** [comment]
me too but GitHub is smarter than expected :)

**Comment by psi29a** [comment]
We released yet?

**Comment by psi29a** [comment]
You think we could be ready for Debian/Ubuntu?  I can create an ITP to get us in, I'm the maintainer of several packages.

https://qa.debian.org/developer.php?login=psi29a@gmail.com

**Comment by ftomassetti** [comment]
We still need to release it on pypi (doing it now). I think it would be amazing to have packages for debian/ubuntu and it could help get some more attention also

**Comment by ftomassetti** [comment]
released! https://pypi.python.org/pypi/worldengine

Anything else to do?

**Comment by psi29a** [comment]
You need to upload not just the whl but the package too!
Do you mind adding me to the pypi package maintainership?  psi29a <--

**Comment by psi29a** [comment]
$ python setup.py sdist upload  # source distribution (for those without wheels)
$ python setup.py bdist_wheel upload # wheel distribution

**Comment by ftomassetti** [comment]
sorry, I just run register. Now I uploaded manually the file, while I uploaded the wheel file as generated by AppVeyor (even if probably in this case it does not matter because there is no stuff compiled).

You should be now an owner of the project on pypi

**Comment by psi29a** [comment]
You only need to register once. :) It took our readme file and tried to display it, we'll have to fix that or make a file specifically for pypi.

**Comment by ftomassetti** [comment]
I think we can edit it directly on Pypi (which seems not reachable right now)

**Comment by ftomassetti** [comment]
Should we close this one now?

**Comment by psi29a** [comment]
Yup
