### ISSUE TITLE
"--ocean-level" parameter didn't seem to do anything

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#116]
I also remember that the "--ocean-level" parameter didn't seem to do anything. Any value down to 0.0001 (the generation cancelled with a value of 0) resulted in approximately the same amount of blue on the ocean map (although I might misunderstand what the parameter is actually supposed to do).

(reported by Stephan)

**Comment by tcld** [comment]
I already created my very own issue for this, but your help is appreciated. :)
https://github.com/Mindwerks/worldengine/issues/114

I included some ocean maps there to provide a quick overview of the problem.

PS: I am the person you just exchanged e-mails with.^^

**Comment by tcld** [comment]
This could technically be closed since it doesn't really contain any more information than #114 .
