### ISSUE TITLE
Produce a sort of "satellite" view of the world

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#169]
On Reddit they suggested us to produce something like this:
http://www.satellite-images.com/images/world32k.jpg

**Comment by esampson** [comment]
That would be very easy to implement. Use the biome map routine, replace the colors with more realistic ones, and draw ice in the oceans (I would find the threshold temperature for polar climate zones and shift it by a small bit. I forget if you need to shift it up or down).

I don't think you are seeing any real shading from elevations directly. I think most of the effect is generated by things such as the wind shadow.

**Comment by esampson** [comment]
BTW, unless I am missing something it doesn't appear we are using any sort of wind shadow effect at all (although we say in the README.md that we do).

**Comment by ftomassetti** [comment]
@esampson you are right. I have implemented it a certain point but perhaps it was even in the project before lands... we should implement this and the prerequisite is to simulate winds. We were caught in things like producing the binaries, testing and so on and for a long time we did not work on features, such as #13 and #14 

Time to go back and finish that!

**Comment by ftomassetti** [comment]
This is done
