### ISSUE TITLE
Add property decorators in World

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#209]
For example:

```python
@property
def elevation:
    return self.layers['elevation'].data
```

**Comment by tcld** [comment]
It might not hurt if you add this to #207, if you can spare the time. By "add" I mean "create all necessary functions and then replace every use of any layer throughout the code with a call to the corresponding property".

Also, do you need to explicitly create a setter, too?
```
@property
def elevation(self):
    return self.layers['elevation'].data

@elevation.setter
def elevation(self, value):
    self.layers['elevation'].data = value
```

**Comment by ftomassetti** [comment]
Me and Bret discussed it and we would prefer to go by steps: so we first merge #207 and then introduce property decorators. I am not sure about the setters perhaps it could make sense given we had all those set_ocean, set_temperature methods to replace

**Comment by psi29a** [comment]
Thanks for this @tcld it is good plan. :)

**Comment by Himura2la** [comment]
I'm going to convert to properties all functions that starts with `set_`. I'll also try to fins their `get_` brothers
