### ISSUE TITLE
Can WorldEngine participate in Google Summer of Code?

### ISSUE THREAD

**Issue by tcld** [Mindwerks/worldengine#221]
Hey there, @ftomassetti and @psi29a . I am not sure if it would be possible for a project of this size or WorldEngine specifically, but do you think that WorldEngine could maybe participate in this years [GSoC](https://summerofcode.withgoogle.com/)?
I am currently looking into whether I could apply as a student and thought it would be great to see WorldEngine amongst the participants. :)

[Here](https://summerofcode.withgoogle.com/terms/org) are some information about the requirements for "mentoring organizations", the deadline for applications is on [February 19th](https://developers.google.com/open-source/gsoc/timeline).

**Comment by ftomassetti** [comment]
This was something I wanted to look into. Until I forgot :D 
We can try, in worst case they will reject us

**Comment by tcld** [comment]
Ah, so the idea isn't a complete surprise.^^
It's certainly worth a try, and it could be very beneficial for WorldEngine. :)

**Comment by psi29a** [comment]
I like this idea. :)

**Comment by ftomassetti** [comment]
@psi29a you should get the invitation to write the application :)

**Comment by Mec-iS** [comment]
Cool. If you need some backups for the initiative I am into it (:

**Comment by ftomassetti** [comment]
Thanks @Mec-iS We now need to create a page with the ideas we propose to work on

**Comment by tcld** [comment]
Aside from polishing/adding sub-simulations, a complete UI might be an idea to think about. The programs overall architecture is probably fine after its recent improvements (which, by the way, should be merged at some point! #214 especially), so purely technical work might not be too necessary.

**Comment by tcld** [comment]
Anything going on about this?

**Comment by ftomassetti** [comment]
Yes, we created the request. The request refers to this wiki page: https://github.com/Mindwerks/worldengine/wiki/Ideas-for-new-contributors so feel free to improve it!

**Comment by tcld** [comment]
Ah, this is great! Should I come up with ideas, I will certainly not keep them for myself.^^ Maybe one of the simulations could use some focussed work? I suspect that any of the simulations would be very fun to work on for a newcomer. There is a scientific part during which one has to read up on how things work on Earth, then some planning and abstraction, then the coding. The ice-cap generation, for example, right now is basically nothing but eyecandy. One could simulate ice-thickness etc. - I'm not sure how much work it would be (probably not too much), but there is certainly room for improvement.

**Comment by ftomassetti** [comment]
Just consider that the evaluation will start from saturday, so whenever you come up with ideas just add them there.

**Comment by psi29a** [comment]
Still need/want a logo for our project though. ;)

**Comment by ftomassetti** [comment]
Well, I had to put something to have a valid application, so I just uploaded the map generated with seed 1 :D I am very open to suggestions for improvements

**Comment by psi29a** [comment]
haha, I'm talking with that chap with the nice logo. I'm hoping to hear back from him soon.

**Comment by psi29a** [comment]
Logo found! :)

![Image of World Engine]
(https://dl.dropboxusercontent.com/u/396161/World_Engine_Logo-01.png)

**Comment by tcld** [comment]
That looks really nice! :)

**Comment by psi29a** [comment]
Send your thanks to http://zacharycorzine.com/ :) 

He donated one of his logos to us.

**Comment by Mec-iS** [comment]
Yea,  real cool :+1:

**Comment by ftomassetti** [comment]
Guys, unfortunately the application was rejected. Let's see if we can get some feedback.

Anyway we got a nice logo out of it :D

**Comment by tcld** [comment]
That's sad news but, yes, the logo is still quite a nice outcome.^^ Has any reasoning been given as to why WorldEngine wasn't accepted?

**Comment by ftomassetti** [comment]
> Thank you for applying to be a Google Summer of Code 2016 mentor organization. Sadly, we were unable to accept Worldengine this year. We had many more applications than we had available slots this year but we do hope you will apply again in the future.

Not super helpful :D

**Comment by psi29a** [comment]
Good news is that we have a hella-awesome logo! :D
