### ISSUE TITLE
Windows release build

### ISSUE THREAD

**Issue by psi29a** [Mindwerks/worldengine#222]
This is a running log of interesting bits when setting up my dev environment in win7.

Got this while trying to install numpy via pip install.
>     c:\python27\Lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'define_macros'
>       warnings.warn(msg)
>     running install
>     running build
>     running config_cc
>     unifing config_cc, config, build_clib, build_ext, build commands --compiler options
>     running config_fc
>     unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
>     running build_src
>     build_src
>     building py_modules sources
>     building library "npymath" sources
>     No module named msvccompiler in numpy.distutils; trying from distutils
>     error: Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat). Get it from http://aka.ms/vcpython27

Looks like we can get MVC++9 for Python from microsoft... and build numpy yourselves instead of installing someone else's precompiled stuff. Testing it out now... should help us with appveyor as well.

**Comment by psi29a** [comment]
Looks like the 84MiB download from http://aka.ms/vcpython27 did the job. ;)

> Building wheels for collected packages: numpy
>   Running setup.py bdist_wheel for numpy: started
>   Running setup.py bdist_wheel for numpy: still running...
>   Running setup.py bdist_wheel for numpy: still running...
>   Running setup.py bdist_wheel for numpy: still running...
>   Running setup.py bdist_wheel for numpy: still running...
>   Running setup.py bdist_wheel for numpy: finished with status 'done'
>   Stored in directory: C:\Users\psi29a\AppData\Local\pip\Cache\wheels\4b\cb\75\2cf74e8d40c2f6e466c621d598769f961bbb0feac948013dfb
> Successfully built numpy
> Installing collected packages: numpy, pypng, PyPlatec, protobuf, six
> Success

**Comment by psi29a** [comment]
Sadly h5py (hdf5) won't install that easily under windows. Going to h5py's website/pypi will only net you the win32 builds. I had to use the unofficial builds located here:
http://www.lfd.uci.edu/~gohlke/pythonlibs/#h5py

**Comment by psi29a** [comment]
> psi29a@win7 MINGW64 ~/Workspace/worldengine/dist/worldengine (master)
> $ ./worldengine.exe
> Traceback (most recent call last):
>   File "<string>", line 11, in <module>
>   File "c:\users\psi29a\workspace\worldengine\venv\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 276, in load_module
>     exec(bytecode, module.__dict__)
>   File "C:\Users\psi29a\Workspace\worldengine\build\worldengine\out00-PYZ.pyz\pkg_resources", line 75, in <module>
>   File "C:\Users\psi29a\Workspace\worldengine\build\worldengine\out00-PYZ.pyz\pkg_resources.extern", line 60, in load_module
> ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.


OK....

> psi29a@win7 MINGW64 ~/Workspace/worldengine (master)
> $ pip install packaging
> Collecting packaging
>   Downloading packaging-16.3-py2.py3-none-any.whl
> Requirement already satisfied (use --upgrade to upgrade): six in c:\users\psi29a\workspace\worldengine\venv\lib\site-packages (from packaging)
> Collecting pyparsing (from packaging)
>   Downloading pyparsing-2.1.0-py2.py3-none-any.whl
> Installing collected packages: pyparsing, packaging
> Successfully installed packaging-16.3 pyparsing-2.1.0
> (venv)

Still no dice... :/

**Comment by psi29a** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=15336

**Comment by psi29a** [comment]
Did the same thing with gdal:
http://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal

**Comment by psi29a** [comment]
> psi29a@win7 MINGW64 ~/Workspace/worldengine/dist/worldengine (master)
> $ ./worldengine.exe
> Traceback (most recent call last):
>   File "<string>", line 11, in <module>
>   File "c:\users\psi29a\workspace\worldengine\venv\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 276, in load_module
>     exec(bytecode, module.__dict__)
>   File "C:\Users\psi29a\Workspace\worldengine\build\worldengine\out00-PYZ.pyz\pkg_resources", line 75, in <module>
>   File "C:\Users\psi29a\Workspace\worldengine\build\worldengine\out00-PYZ.pyz\pkg_resources.extern", line 60, in load_module
> ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.

OK...

cp venv/Lib/site-packages/packaging dist/worldengine/ -fr

and boom!

> psi29a@win7 MINGW64 ~/Workspace/worldengine/dist/worldengine (master)
> $ ./worldengine.exe
> Unable to load GDAL support, no heightmap export possible.
> Worldengine - a world generator (v. 0.19.0)
> -----------------------
>  operation            : world generation
>  seed                 : 45664
>  name                 : seed_45664
>  width                : 512
>  height               : 512
>  number of plates     : 10
>  world format         : protobuf
>  black and white maps : False
>  step                 : full
>  greyscale heightmap  : False
>  icecaps heightmap    : False
>  rivers map           : False
>  scatter plot         : False
>  satellite map        : False
>  fade borders         : True
>  gamma value          : 1.25
>  gamma offset         : 0.2
> 
> starting (it could take a few minutes) ...
> 
> Producing ouput:
> * world data saved in './seed_45664.world'
> * ocean image generated in './seed_45664_ocean.png'
> * precipitation image generated in './seed_45664_precipitation.png'
> * temperature image generated in './seed_45664_temperature.png'
> * biome image generated in './seed_45664_biome.png'
> * elevation image generated in './seed_45664_elevation.png'
> ...done

**Comment by psi29a** [comment]
https://github.com/Mindwerks/worldengine/releases/download/untagged-57586cacf7d0cb6bffe3/worldengine-0.19.0-Windows_x86_64.zip

**Comment by Strogg** [comment]
Hi, this link 404's for me. I'm very interested in an executable for the latest version, so if you could fix the link I would really appreciate it.

**Comment by psi29a** [comment]
Sorry, I posted it here from my dropbox:
https://github.com/Mindwerks/worldengine/issues/184#issuecomment-187420235

Let me know if you have any issues. It is a 64-bit build.

**Comment by Strogg** [comment]
Awesome, many thanks!
