### ISSUE TITLE
OSX Build Clarification re: Protobuf

### ISSUE THREAD

**Issue by PeteMichaud** [Mindwerks/worldengine#231]
> At this time, it doesn't gather everything from protobuf. So you'll need to copy google/protobuf python to dist/google/protobuf and create init.py in dist/google

I'm not sure what this means -- where and what is "google/protobuf python"? There is no `dist` folder, so I'm guessing the idea is to create the `dist/google/protobuf` folder under the main worldengine folder? And I'm assuming `init.py` in the new`dist/google` folder is just a blank file?

**Comment by psi29a** [comment]
This is about building a package of WE with pyinstaller. You don't need this to run WE.

At that point in time, pyinstaller would not copy your google/protobuf directory to dist/google/protobuf. So you had to do it manually. This is after you ran pyinstaller.

Note: you don't need to do this if you aren't building a release. I've already made a release for you, it is in the releases page:
https://github.com/Mindwerks/worldengine/releases

**Comment by PeteMichaud** [comment]
Thanks! Yeah, I'm trying to get the build working so I can potentially make modifications, including the potential bug and the potential new feature I mentioned in my other open issues.
