### ISSUE TITLE
Error installing Python Image Library using pip on Mac OS X 10.9

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#26]
See http://stackoverflow.com/questions/20325473/error-installing-python-image-library-using-pip-on-mac-os-x-10-9
maybe we could use Pillow instead of PIL.

We have to look into CI on Mac

**Comment by cesarramirez** [comment]
I will look into making some changes for changing from PIL to Pillow. I will get back when I have some updates.

**Comment by ftomassetti** [comment]
@stefan-feltmann already moved the project to Pillow, I should have closed this issue (I am doing it now).

Anyway there are still plenty of possible improvements, including the one you suggested :D

We are _extremely_ open to contributions a new ideas
