### ISSUE TITLE
Export to .ter (Terragen) format

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#32]

**Comment by psi29a** [comment]
http://www.planetside.co.uk/terragen/dev/tgterrain.html  <-- file format params

We should allow for import and export.

**Comment by psi29a** [comment]
http://planetside.co.uk/wiki/index.php?title=Terragen_Import-Export_Reference

**Comment by psi29a** [comment]
Mine... i like file formats. (Like with my WildMIDI project)

**Comment by ftomassetti** [comment]
Good :D

**Comment by psi29a** [comment]
Ohhhhhh... http://www.gdal.org/formats_list.html via https://pypi.python.org/pypi/GDAL/ supports more file formats than you can shake a stick at.

**Comment by ftomassetti** [comment]
ball - match - game - victory!

**Comment by psi29a** [comment]
How do we want to go about this?

I'm thinking that want want to take what is in the *.world file and export the data in there to gdal (for TER).

This means that you would first generate your world, then run: worldgen --export ter your.world
and the default behaviour would to just take the heightmap and convert it your.ter

We can also provide a mechnism to specify which dataset in *.world, so not just the heightmap.

What do you think?

**Comment by ftomassetti** [comment]
yes, it works for me. By default we should keep using our format and export to other as a separate action

**Comment by psi29a** [comment]
Agreed! :)

**Comment by psi29a** [comment]
Virtualenv and setuptools friendly version of standard GDAL python bindings
https://pypi.python.org/pypi/pygdal

**Comment by ftomassetti** [comment]
I think this one is done right @psi29a ?

**Comment by psi29a** [comment]
yes and no, the ter support in gdal is currently broken.  however, in Terragen you can import heightmap from any number of formats already supported by gdal.  How do you feel about closing this?

**Comment by ftomassetti** [comment]
Let's close it: we already support a lot of stuff :)
