### ISSUE TITLE
Support .hfz height-field format

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#33]

**Comment by ftomassetti** [comment]
Should we close this one @psi29a ?

**Comment by psi29a** [comment]
Normally yes, http://www.gdal.org/frmt_hf2.html

I haven't tested it yet.

**Comment by psi29a** [comment]
(venv)bcurtis@Wintermute:~/workspace/WorldEngine/worldengine$ python worldengine export seed_60070.world --export-type HF2 --export-bpp 32 --export-signed
Worldengine - a world generator (v. 0.18.0)
-----------------------
 operation         : export generation
 name               : seed_60070
 width              : 512
 height             : 512
 seed               : 60070
 no plates          : 10
 ocean level        : 1.000000
 step               : plates
 has biome          : True
 has humidity       : True
 has irrigation     : True
 has permeability   : True
 has watermap       : True
 has precipitations : True
 has temperature    : True
...done

(venv)bcurtis@Wintermute:~/workspace/WorldEngine/worldengine$ gdalinfo  seed_output-32.HF2 
Driver: HF2/HF2/HFZ heightfield raster
Files: seed_output-32.HF2
Size is 512, 512
Coordinate System is `'
Origin = (0.000000000000000,0.000000000000000)
Pixel Size = (1.000000000000000,1.000000000000000)
Metadata:
  VERTICAL_PRECISION=0.010000
Corner Coordinates:
Upper Left  (   0.0000000,   0.0000000) 
Lower Left  (       0.000,     512.000) 
Upper Right (     512.000,       0.000) 
Lower Right (     512.000,     512.000) 
Center      (     256.000,     256.000) 
Band 1 Block=256x1 Type=Float32, ColorInterp=Undefined
  Unit Type: m

Tested :)
