### ISSUE TITLE
Cross compile for windows

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#39]
Take a look at:
http://gwyddion.net/documentation/user-guide-en/installation-cross-mingw32.html

**Comment by ftomassetti** [comment]
Maybe we can create a docker image with wine using https://github.com/ogrisel/python-winbuilder

**Comment by ftomassetti** [comment]
Also this one is interesting:
http://cyrille.rossant.net/create-a-standalone-windows-installer-for-your-python-application/

**Comment by ftomassetti** [comment]
This seems very interesting (using aws for free) http://cowboyprogrammer.org/building-python-wheels-for-windows/

**Comment by psi29a** [comment]
Using the information above, we can use http://www.appveyor.com/

**Comment by ftomassetti** [comment]
how, just noticed that appveyor is free for OSS. I thought it wasn't

**Comment by ftomassetti** [comment]
guess what... there are problems compiling pyplatec (which uses C++ '11). To be compatible with python we have to use certain versions of the compiler and I am afraid they do not support C++ '11 so we will have to remove the C++ '11 features (which are very limited anyway), so let's pause that until we fix pyplatec...

**Comment by psi29a** [comment]
yeah... msvc isn't c++11 complient. we'll likely have to use mingw to either compile natively on windows or on linux as a cross compile... which is actually a good thing. ;)

http://www.mingw.org/
http://sebsauvage.net/python/mingw.html
https://bitbucket.org/puqing/python-mingw

**Comment by ftomassetti** [comment]
Ok, we have python wheels for PyPlatec, now we could run bdist_msi.
We can also take a look at:
http://pynsist.readthedocs.org/en/latest/ (see this for a script https://github.com/acutesoftware/dev_setup/blob/master/make_inst.py)

http://nuitka.net/

https://freepythontips.wordpress.com/2014/03/03/using-py2exe-the-right-way/

https://sxbo672158.wordpress.com/2012/01/21/py2exe-pyinstaller-build-executable-file-for-your-python-script/

**Comment by psi29a** [comment]
Yay!

**Comment by ftomassetti** [comment]
ok, we have our AppVeyor working for us, should be close this one?

**Comment by psi29a** [comment]
Double yay!  and yes.

**Comment by ftomassetti** [comment]
Closing then :)
