### ISSUE TITLE
Export to Photoshop format (PSD)

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#49]
On Reddit it has been suggested to support PSD files.

"I feel that a really vital tool could be creating an easy export to photoshop, complete with layer integrity -- ie, a terrain layer, an elevation layer, a water layer, and a line map layer (most important!)"

**Comment by psi29a** [comment]
Is PSD an open and documented format?

**Comment by ftomassetti** [comment]
There are specs here: http://www.adobe.com/devnet-apps/photoshop/fileformatashtml/
We could also consider supporting formats which are opened by Photoshop.
In addition/alternative we could support the Gimp format.

**Comment by ftomassetti** [comment]
Another user has suggested supporting tiff instead (which should be open also by Gimp and support layers)

**Comment by psi29a** [comment]
Honestly, just use the Qt library... it is what I used. It handles almost all known formats. :)  For the most exotic formats, we'll have to include those separately.

The big ones for me are: bmp, png (8 and 16 bit greyscale), tiff, raw (8, 16, 32 bits)

**Comment by ftomassetti** [comment]
good to know that the QT library can help. I think however that only tiff supports multi layer images (so that we can store elevation, wind, temperature and so on in one file)

**Comment by ftomassetti** [comment]
Probably we do not need this one after all, I would close it. Please re-open if needed
