### ISSUE TITLE
Error with the Greyscale file generation

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#55]
As reported by Ryan

Downloaded the latest master and installed on Windows x64 with no issue. However, when trying to generate a Greyscale file with the current master build, it failed to produce the file with this error:
```
Traceback (most recent call last):
  File "C:\Python27\Scripts\worldengine-script.py", line 9, in <module>
    load_entry_point('worldengine==0.5.4', 'console_scripts', 'worldengine')()
  File "build\bdist.win-amd64\egg\worldengine\cli\main.py", line 304, in main
  File "build\bdist.win-amd64\egg\worldengine\cli\main.py", line 71, in generate_grayscale_heightmap
  File "build\bdist.win-amd64\egg\worldengine\draw.py", line 207, in draw_grayscale_heightmap
AttributeError: 'str' object has no attribute 'set_pixel'`
```

Any obvious reason why that is failing, or is it an issue/incomplete feature with the current build?

**Comment by tcld** [comment]
I think this can be closed. And I am not sure if I should go around posting messages like this.^^

Heightmap-export of various forms worked ok with the current master-branch.

**Comment by ftomassetti** [comment]
Your opinion is always welcome and we are very thankful for your efforts on the project.
Should this be closed because the relevant pieces of code changed in the meantime?

**Comment by tcld** [comment]
Well, I am not sure where exactly the problem started, but the export works fine at the moment and the issue has been reported a long time ago. Yesterday I worked my way through draw.py and everything looks good to me.

If you want to wait for changes to the file before closing this, then let's wait until https://github.com/Mindwerks/worldengine/pull/141 is finished. (Although that branch is based on https://github.com/Mindwerks/worldengine/pull/138, so there is not much use in looking at it yet.)

**Comment by psi29a** [comment]
This was fixed by me awhile ago... it wasn't the only issue open about the problem. ;) 

So we can close this.
