### ISSUE TITLE
Ocean floor have a lot of noise applied to them

### ISSUE THREAD

**Issue by cesarramirez** [Mindwerks/worldengine#60]
The ocean floor have very heavy noise applied to them. This looks very unrealistic since the ocean floor is much more flat. I see how we need the noise to make the surfaces more realistic but we may want to reduce the amount of noise applied to the ocean surface compared to the land.

I am attaching this pictures to show what I am taking about:
http://imgur.com/ShhMnV2,FOhmUey#0
http://imgur.com/ShhMnV2,FOhmUey#1

**Comment by ftomassetti** [comment]
Hi Cesar, you are right. The problem should be limited using the new version of PyPlatec (about to be released). After that we will see how the situation improves and dig more into this. Thanks for reporting it.

**Comment by ftomassetti** [comment]
Close via #150

**Comment by ftomassetti** [comment]
Thanks for reporting this one @cesarramirez , it took a while but we fixed. Soon we will release the new version of WorldEngine with this fix and many, many improvements!
