### ISSUE TITLE
Stop using noise package

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#61]
The noise package has not python wheels for Windows (I sent a patch to fix this but the owner has not time to revise it :( ).
We could just expose noise functions from plate-tectonics instead.

Or create a fork of noise just to be able to upload wheels to Pypi.

**Comment by psi29a** [comment]
I have his email... remind me tomorrow and I'll try to contact him.  I've a very particular set of skills...

**Comment by ftomassetti** [comment]
Perfect, I will send you an e-mail with all the details tomorrow

**Comment by ftomassetti** [comment]
Solved by @psi29a, see #62
