### ISSUE TITLE
Alternatives for packaging on Windows

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#68]
We could consider building conda packages for windows: hopefully it should make life easier. According to this: http://stackoverflow.com/questions/20994716/what-is-the-difference-between-pip-and-conda

it should also takes care of other tools (not only python packages) such as compilers and libraries. Maybe we can use it to package QT and Python itself.

**Comment by ftomassetti** [comment]
For examples there are recipes for installing PyQt: https://github.com/conda/conda-recipes/blob/master/pyqt/bld.bat

**Comment by ftomassetti** [comment]
We could also consider creating installers based on WinPython: http://cyrille.rossant.net/create-a-standalone-windows-installer-for-your-python-application/

**Comment by SourceRyan** [comment]
For what it's worth, I am creating updated instructions for windows as we speak. I have found that the availability of .whl files has greatly simplified the installation for end-users.

**Comment by psi29a** [comment]
+1 :)

**Comment by ftomassetti** [comment]
Glad to hear that the whl files are helping :) Thank you for updating the instructions for windows: I really appreciate that!

**Comment by psi29a** [comment]
Related to my work on PyInstaller:
https://github.com/Mindwerks/worldengine/issues/82

**Comment by psi29a** [comment]
Seems we have a winner!
