### ISSUE TITLE
Improve/extract erosion

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#8]
It could be a standalone library, maybe written in C.
Or maybe I could use some existing library, if it exists.

**Comment by ftomassetti** [comment]
There is also the  worldsynth implementation which is interesting

**Comment by rbb** [comment]
The [worldsynth](http://www.mindwerks.net/projects/worldsynth/) is interesting stuff. Especially the [height map generation](http://freespace.virgin.net/hugo.elias/models/m_landsp.htm), based on spheres. Would you take that (spherical) height map and run it through a projection (mercator, etc), or do you have ideas on how to implement the height map algorithm for a planar surface?

Also, their use of [PyTables](http://www.pytables.org/) is interesting, as it claims to be even faster than using memmap() on numpy structures.

**Comment by ftomassetti** [comment]
I wrote to Bret Curtis (the maintainer of worldsynth) and we are considering merging the projects, so we could use that implementation. Currently worldsynth is under GPL but the author is considering to move to MIT (which would make it compatible with Lands). I also tried to play with the rivers+erosion code present in worldsynth in a separate branch (https://github.com/ftomassetti/lands/tree/worldsynthrivers) and it seems fairly doable to integrate it.

Let's see what Bret thinks about it, either way we should start a mailing list to discuss ideas and roadmaps with everyone interested in contributing

**Comment by rbb** [comment]
Sounds like a plan. I'm not going to implement any PyTables or bumpy stuff until the dust settles.

**Comment by rbb** [comment]
FYI, I ran across another generator, which I think is based on particle deposition, over at [pygame](http://www.pygame.org/project-heightfield-2204-.html)

**Comment by ftomassetti** [comment]
well, we are moving forward with the merge :)

**Comment by rbb** [comment]
Sweet. Let me know if there is anything I can do.

**Comment by ftomassetti** [comment]
sure, I will! I think there will be plenty of work to do and I would very much appreciate your help. I think @psi29a is going to change the license of WorldSynth so that we can start include code from it

**Comment by ftomassetti** [comment]
[WorldSynth](https://github.com/psi29a/worldsynth) is now licensed under MIT License!

**Comment by psi29a** [comment]
Numpy is awesome and I used pytables because of it's ability to write out and read in HDF5 which _the_ standard for scientific (floating point precision) datasets.
https://en.wikipedia.org/wiki/Hierarchical_Data_Format

It is wicked fast and fits easily into numpy. I suggest it as the default way to handle multiple large datasets.

**Comment by ftomassetti** [comment]
Is it something to use only for in memory representation or is it also a space-efficient format to save on disk?

**Comment by psi29a** [comment]
It is both. It is also plugable to include compression and/or encryption if necessary. You can query the dataset direct from disk, so as to not load everything in.

It was made explicitly for the types of things we are working with. Large homogeneous datasets.

**Comment by ftomassetti** [comment]
We should use it then!

**Comment by ftomassetti** [comment]
Ok, we have now the WorldSynth inherited erosion :D
Closing

**Comment by psi29a** [comment]
yay!
