### ISSUE TITLE
Evaluate PyInstaller for Windows

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#82]
We should create a venv, install the libraries, zip the content and distribute it

**Comment by psi29a** [comment]
We got this working under Linux, in theory it should work on Windows as well. I'll give this a spin when the chance presents itself.

**Comment by psi29a** [comment]
We got a working binary here:
https://dl.dropboxusercontent.com/u/396161/worldengine-windows-x86_64.tar.bz2

testing welcome. :)

**Comment by ftomassetti** [comment]
I will post it on reddit and our Google group

**Comment by psi29a** [comment]
The python.h warning is a known issue.

**Comment by psi29a** [comment]
I would say that this was a success. :)
