### ISSUE TITLE
Evaluate py2app for Mac

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#83]

**Comment by psi29a** [comment]
According to everyone everywhere (google), the only real solution is py2app. Someone with a Mac should help volunteer to test this. :)

**Comment by psi29a** [comment]
I have py2app installed, but I also have pyinstaller...  trying out the later now. Can someone please test this:
https://dl.dropboxusercontent.com/u/396161/worldengine-mac-x86_64.tar.bz2

Let me know if it works and/or has issues. :)

**Comment by ftomassetti** [comment]
I have not a mac available. I will buy one when I start my own company but if we find someone to test it before it would be great

**Comment by rbb** [comment]
I can test it. I assume the thing to test is the link posted by psi29a?

**Comment by ftomassetti** [comment]
Yes! It would be great!

**Comment by rbb** [comment]
Is there anything in particular that I should be testing for? Just that it runs?

**Comment by ftomassetti** [comment]
yes, just that it run: we want to understand if this way of packaging applications work, if all the dependencies are included etc.

If it starts and run without crashing we are happy for the time being :)

**Comment by rbb** [comment]
Yup. Seems to work.

`./worldengine -n myworld -g out
Worldengine - a world generator (v. 0.18.0)
-----------------------
 operation         : world generation
 seed                 : 30824
 name                 : myworld
 width                : 512
 height               : 512
 number of plates     : 10
 world format         : pickle
 black and white maps : False
 step                 : full
 (no greyscale heightmap)
 (no rivers map)

starting (it could take a few minutes) ...

Producing ouput:
* world data saved in './myworld.world'
* ocean image generated in './myworld_ocean.png'
* precipitation image generated in './myworld_precipitation.png'
* temperature image generated in './myworld_temperature.png'
* biome image generated in './myworld_biome.png'
* elevation image generated in './myworld_elevation.png'
...done
russell@Neko:~/Downloads/worldengine-mac-x86_64
$ lt
total 91464
-rwxr-xr-x@ 1 russell  staff   8.8M Jul  8 09:10 worldengine
drwxr-xr-x@ 5 russell  staff   170B Jul  8 09:14 google
-rw-r--r--  1 russell  staff    11K Jul 13 11:18 myworld_ocean.png
-rw-r--r--  1 russell  staff    35M Jul 13 11:18 myworld.world
-rw-r--r--  1 russell  staff    11K Jul 13 11:18 myworld_precipitation.png
-rw-r--r--  1 russell  staff    35K Jul 13 11:18 myworld_temperature.png
-rw-r--r--  1 russell  staff    26K Jul 13 11:18 myworld_biome.png
-rw-r--r--  1 russell  staff   317K Jul 13 11:18 myworld_elevation.png`

**Comment by ftomassetti** [comment]
Great to hear that! Thanks for testing!

**Comment by psi29a** [comment]
Yay!

**Comment by ftomassetti** [comment]
Ok, then I guess we can close this issue. Thank you @psi29a and @rbb !
