### ISSUE TITLE
Consider PyInstaller 

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#85]
If it works, list the project under:
https://github.com/pyinstaller/pyinstaller/wiki/Projects-Using-PyInstaller

The executable can also be signed under Windows:
https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Win-Code-Signing

**Comment by psi29a** [comment]
Going to investigate how veusz does it, as they use pyqt as well.

https://github.com/jeremysanders/veusz

**Comment by ftomassetti** [comment]
great, I think this is the most crucial aspect to release our first version

**Comment by ftomassetti** [comment]
(closed by mistake, sorry)

**Comment by psi29a** [comment]
No worries, I just sent an email asking a few questions about how they do it.

From what I see, for OSX they use py2app and put all relevant information in the setup.py file.

For windows, it seems they use a combination NSIS (to make an installer) and PyInstaller to get gather all the libs/binaries into one place.

The question now is, what magic combination of trickery allowed for this to happen.

**Comment by psi29a** [comment]
Was able to produce a single binary that I've tested on two locations, sent to @ftomassetti and another friend and they all run. I consider this a success and have added documentation.

It is in this PR:
https://github.com/Mindwerks/worldengine/pull/102

I'm closing this issue. :)
