### ISSUE TITLE
Create Java bindings

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#87]
We should create a Java library which permit to load world files.
Ideally we may want to release it on Maven.
Does it make sense @psi29a ?

**Comment by ftomassetti** [comment]
I started creating this project: https://github.com/ftomassetti/worldengine-java
If it makes sense for you we could move it under Mindwerks

**Comment by psi29a** [comment]
Be my guest, however I want to be honest, I'll be hands off on Java. :)

**Comment by ftomassetti** [comment]
Moved
