### ISSUE TITLE
Support HDF5

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#91]
We should be able to read and write worlds in the HDF5 format

**Comment by ftomassetti** [comment]
Steal it from WorldSynth

**Comment by psi29a** [comment]
yeah, liberate my own work :P

**Comment by psi29a** [comment]
We support the HDF4/5 format in export, but I think we want to use HDF5 (pytables) instead of protobuf.

**Comment by ftomassetti** [comment]
Exactly what I wrote on #65. In export I guess we consider just the elevation map, right? I am thinking about all the data

**Comment by psi29a** [comment]
We can now export to HDF4/5 (also same for ther formats, so this effect multiple issues)
Import will likely take a bit of work. ;)

**Comment by ftomassetti** [comment]
oh, it is already implemented? We do too many things I missed this :)
However are we supporting through GDAL exporting just the elevation map? I was working on creating an HDF5 file with _all_ the data we currently export to protobuf or pickle

**Comment by psi29a** [comment]
Honestly, I'm steering towards protobuf if it does indeed offer python2/3 compatibility.

**Comment by ftomassetti** [comment]
Right but right now there is an issue that cause me to not be able to load from Java protobuf worlds generated from WorldEngine (#151). As far as I can understand it should be solved when 3.0.0 is properly released. In my initial experiments with HDF5 it seems quite easy to support it, so perhaps we could have support ALSO for HDF5 and that would be particularly useful until protobuf is finalized.

Do you think it is not worthy the trouble having more formats? I admit it could be confusing for the user to support several formats, especially if we use the same extension. Perhaps we could use something like foo.hdf5.we and bar.pb.we

**Comment by psi29a** [comment]
If you want it, got for it. :)  HDF5 is great for storing data-sets... but no so much for meta-data.  How far along are you?

**Comment by ftomassetti** [comment]
well, writing the serialization was easy. Writing the unserialization and a test took a bit but I am about to send the PR now
