### ISSUE TITLE
Document a-star

### ISSUE THREAD

**Issue by ftomassetti** [Mindwerks/worldengine#97]
Comment from Bret:
"Astar works on cost, the higher the cost the less likely it is to travel that path. There are no hard limits, it works on minus infinity and positive infinity. It will take a starting position and and end position, then find the path between the two with the lowest cost. This is perfect for heightmaps for example, because you can use it to find path through mountain/hills between villages. ;)"

**Comment by psi29a** [comment]
https://github.com/Mindwerks/worldengine/commit/d36e2fde0c8505822b8b7ef2493f3d1b8311f1e9
